defmodule ThesisMonitor.Commands.Init do
  @moduledoc """
  セットアップコマンド

  設定ファイル（~/.config/thesis-monitor/config.yml）の生成と doctor 検証を行う。
  レジストリは GitHub contents API で読む（clone 不要、issue #14。
  ローカル checkout 読みの互換モードは持たない — issue #20）。

  データリポジトリの新規作成はスコープ外（registry-manager の init を案内）。
  """

  alias ThesisMonitor.Output

  @default_org "smkwlab"
  @prod_repo_name "thesis-student-registry"
  @test_repo_name "thesis-student-registry-test"
  @registry_file_path "data/registry.json"

  def run(_args, opts, deps \\ %{}) do
    output = deps[:output] || Output
    gh = deps[:gh] || (&default_gh/1)

    params = resolve_params(opts)

    location = {:api, params.registry_repo}

    with :ok <- check_config_writable(params, output),
         :ok <- write_config(params, location, output) do
      run_doctor(params, location, gh, output)
      show_next_steps(params, output)
      {:ok, params.config_path}
    end
  end

  # --- パラメータ解決 ---

  defp resolve_params(opts) do
    test_mode = opts[:test] || false
    org = opts[:org] || @default_org
    repo_name = if test_mode, do: @test_repo_name, else: @prod_repo_name

    %{
      test_mode: test_mode,
      org: org,
      registry_repo: opts[:registry_repo] || "#{org}/#{repo_name}",
      cache_dir:
        if(test_mode, do: "~/.cache/thesis-monitor-test", else: "~/.cache/thesis-monitor"),
      config_path: opts[:config] || default_config_path(test_mode),
      force: opts[:force] || false
    }
  end

  # --test サンドボックスは意図的に cwd ローカル（本番 config と混ざらない）
  defp default_config_path(true), do: "./thesis-monitor-test.yml"
  defp default_config_path(false), do: ThesisMonitor.Config.default_config_path()

  # --- 設定ファイル ---

  defp check_config_writable(%{config_path: path, force: false}, output) do
    if File.exists?(path) do
      call(output, :error, "Config file already exists: #{path} (use --force to overwrite)")
      {:error, :config_exists}
    else
      :ok
    end
  end

  defp check_config_writable(_params, _output), do: :ok

  defp write_config(params, location, output) do
    content = build_config_yaml(params, location)

    result =
      with :ok <- File.mkdir_p(Path.dirname(params.config_path)) do
        File.write(params.config_path, content)
      end

    case result do
      :ok ->
        call(output, :success, "Wrote config: #{params.config_path}")
        :ok

      {:error, reason} ->
        call(output, :error, "Failed to write config #{params.config_path}: #{reason}")
        {:error, :config_write_failed}
    end
  end

  @doc false
  def build_config_yaml(params, location) do
    """
    # Generated by `thesis-monitor init`#{if params.test_mode, do: " --test", else: ""}
    github_org: #{params.org}

    #{registry_yaml(location, params)}
    cache_dir: #{params.cache_dir}

    # 学生名簿 CSV（任意）。名簿はローカル管理のためリポジトリ・レジストリに置かない。
    # 未設定時は ~/.config/#{params.org}/students.csv を規約として参照（存在時のみ）
    # csv_path: /path/to/students.csv
    """
  end

  # 規約値（<org>/thesis-student-registry）と一致する registry_repo は
  # コメントで書く: 実効値を規約導出に任せ、生成ファイルをドリフト源にしない
  # （issue #16）。--test や --registry-repo の明示値は有効行として書く
  defp registry_yaml({:api, repo}, params) do
    if repo == "#{params.org}/#{@prod_repo_name}" do
      """
      # レジストリデータリポジトリ（owner/repo）。GitHub contents API で読み取る。
      # 未設定時は <github_org>/thesis-student-registry を規約として使用（既定値）
      # registry_repo: #{repo}
      """
    else
      """
      # レジストリデータリポジトリ（owner/repo）。GitHub contents API で読み取る
      registry_repo: #{repo}
      """
    end
  end

  # --- doctor ---

  defp run_doctor(params, location, gh, output) do
    call(output, :puts, "\nDoctor:")

    check(output, "gh auth", gh.(["auth", "status"]), "gh auth login でログインしてください")

    check(
      output,
      "org access (#{params.org})",
      gh.(["api", "orgs/#{params.org}"]),
      "組織 #{params.org} への API アクセスに失敗しました。権限を確認してください"
    )

    check_registry(location, gh, output)
    check_cache_dir(params.cache_dir, output)
  end

  defp check(output, label, result, remedy) do
    case result do
      {:ok, _} -> call(output, :success, "✓ #{label}")
      {:error, _} -> call(output, :warn, "✗ #{label} — #{remedy}")
    end
  end

  # contents API でレジストリファイルの疎通を確認する
  defp check_registry({:api, repo}, gh, output) do
    case gh.(["api", "repos/#{repo}/contents/#{@registry_file_path}"]) do
      {:ok, _} ->
        call(output, :success, "✓ registry access (#{repo}/#{@registry_file_path})")

      {:error, _} ->
        call(
          output,
          :warn,
          "✗ registry access — #{repo} の #{@registry_file_path} を取得できません。" <>
            "リポジトリが未作成の場合は registry-manager の init（bootstrap）で作成してください: " <>
            "https://github.com/smkwlab/registry-manager 。" <>
            "private リポジトリのためトークンの Contents: Read 権限も確認してください"
        )
    end
  end

  defp check_cache_dir(cache_dir, output) do
    expanded = Path.expand(cache_dir)

    case File.mkdir_p(expanded) do
      :ok -> call(output, :success, "✓ cache dir (#{expanded})")
      {:error, reason} -> call(output, :warn, "✗ cache dir #{expanded} — #{reason}")
    end
  end

  # --- 仕上げ ---

  defp show_next_steps(params, output) do
    config_flag =
      if params.config_path == default_config_path(false),
        do: "",
        else: " --config #{params.config_path}"

    call(output, :puts, "\nNext: thesis-monitor status#{config_flag}")
  end

  # --- helpers ---

  defp default_gh(args) do
    case System.cmd("gh", args, stderr_to_stdout: true) do
      {out, 0} -> {:ok, out}
      {out, _} -> {:error, out}
    end
  rescue
    e in ErlangError -> {:error, "gh command not found: #{inspect(e)}"}
  end

  defp call(output, fun, msg) when is_atom(output), do: apply(output, fun, [msg])
  defp call(output, fun, msg) when is_map(output), do: output[fun].(msg)
end
