defmodule ThesisMonitor.Commands.Init do
  @moduledoc """
  セットアップコマンド

  設定ファイル（~/.thesis-monitor.yml）の生成、registry データリポジトリの
  clone（既存 checkout があればパス設定のみ）、doctor 検証を行う。

  データリポジトリの新規作成はスコープ外（registry-manager の init を案内）。
  """

  alias ThesisMonitor.Output

  @default_org "smkwlab"
  @prod_repo_name "thesis-student-registry"
  @test_repo_name "thesis-student-registry-test"
  @registry_file "registry.json"
  @legacy_registry_file "repositories.json"

  def run(_args, opts, deps \\ %{}) do
    output = deps[:output] || Output
    gh = deps[:gh] || (&default_gh/1)

    params = resolve_params(opts)

    with :ok <- check_config_writable(params, output),
         {:ok, registry_dir} <- resolve_registry_dir(params, gh, output),
         :ok <- write_config(params, registry_dir, output) do
      run_doctor(params, registry_dir, gh, output)
      show_next_steps(params, output)
      {:ok, params.config_path}
    end
  end

  # --- パラメータ解決 ---

  defp resolve_params(opts) do
    test_mode = opts[:test] || false
    org = opts[:org] || @default_org
    repo_name = if test_mode, do: @test_repo_name, else: @prod_repo_name

    %{
      test_mode: test_mode,
      org: org,
      registry_repo: opts[:registry_repo] || "#{org}/#{repo_name}",
      registry_dir: opts[:registry_dir],
      # clone 先は実行時の cwd に依存しないよう解決時点で絶対パス化する
      clone_to: Path.expand(opts[:clone_to] || "./#{repo_name}"),
      cache_dir:
        if(test_mode, do: "~/.cache/thesis-monitor-test", else: "~/.cache/thesis-monitor"),
      config_path: opts[:config] || default_config_path(test_mode),
      force: opts[:force] || false
    }
  end

  defp default_config_path(true), do: "./thesis-monitor-test.yml"
  defp default_config_path(false), do: Path.expand("~/.thesis-monitor.yml")

  # --- 設定ファイル ---

  defp check_config_writable(%{config_path: path, force: false}, output) do
    if File.exists?(path) do
      call(output, :error, "Config file already exists: #{path} (use --force to overwrite)")
      {:error, :config_exists}
    else
      :ok
    end
  end

  defp check_config_writable(_params, _output), do: :ok

  defp write_config(params, registry_dir, output) do
    content = build_config_yaml(params, registry_dir)

    case File.write(params.config_path, content) do
      :ok ->
        call(output, :success, "Wrote config: #{params.config_path}")
        :ok

      {:error, reason} ->
        call(output, :error, "Failed to write config #{params.config_path}: #{reason}")
        {:error, :config_write_failed}
    end
  end

  @doc false
  def build_config_yaml(params, registry_dir) do
    """
    # Generated by `thesis-monitor init`#{if params.test_mode, do: " --test", else: ""}
    github_org: #{params.org}

    # レジストリデータリポジトリのローカル checkout 内の data/ ディレクトリ
    registry_dir: #{registry_dir}

    cache_dir: #{params.cache_dir}
    """
  end

  # --- registry checkout の解決 ---

  # 生成する config は実行時の cwd に依存しないよう絶対パスで書く
  defp resolve_registry_dir(%{registry_dir: dir}, _gh, output) when is_binary(dir) do
    if File.dir?(dir) do
      {:ok, Path.expand(dir)}
    else
      call(output, :error, "registry_dir not found: #{dir}")
      {:error, :registry_dir_not_found}
    end
  end

  defp resolve_registry_dir(params, gh, output) do
    data_dir = Path.join(params.clone_to, "data")

    if File.dir?(data_dir) do
      call(output, :info, "Using existing checkout: #{params.clone_to}")
      {:ok, Path.expand(data_dir)}
    else
      clone_registry(params, data_dir, gh, output)
    end
  end

  defp clone_registry(params, data_dir, gh, output) do
    call(output, :info, "Cloning #{params.registry_repo} into #{params.clone_to} ...")

    case gh.(["repo", "clone", params.registry_repo, params.clone_to]) do
      {:ok, _} ->
        verify_cloned_data_dir(data_dir, params, output)

      {:error, reason} ->
        call(
          output,
          :error,
          "Failed to clone #{params.registry_repo}: #{String.trim("#{reason}")}\n" <>
            "リポジトリが存在しない場合は registry-manager の init（bootstrap）で作成してください: " <>
            "https://github.com/smkwlab/registry-manager"
        )

        {:error, :registry_repo_unavailable}
    end
  end

  # clone は成功したが registry の構造（data/）を持たない場合を弾く
  defp verify_cloned_data_dir(data_dir, params, output) do
    if File.dir?(data_dir) do
      {:ok, Path.expand(data_dir)}
    else
      call(
        output,
        :error,
        "#{params.registry_repo} に data/ ディレクトリがありません。" <>
          "レジストリデータリポジトリの初期化には registry-manager の init（bootstrap）を使用してください: " <>
          "https://github.com/smkwlab/registry-manager"
      )

      {:error, :registry_data_missing}
    end
  end

  # --- doctor ---

  defp run_doctor(params, registry_dir, gh, output) do
    call(output, :puts, "\nDoctor:")

    check(output, "gh auth", gh.(["auth", "status"]), "gh auth login でログインしてください")

    check(
      output,
      "org access (#{params.org})",
      gh.(["api", "orgs/#{params.org}"]),
      "組織 #{params.org} への API アクセスに失敗しました。権限を確認してください"
    )

    check_registry_file(registry_dir, output)
    check_cache_dir(params.cache_dir, output)
  end

  defp check(output, label, result, remedy) do
    case result do
      {:ok, _} -> call(output, :success, "✓ #{label}")
      {:error, _} -> call(output, :warn, "✗ #{label} — #{remedy}")
    end
  end

  defp check_registry_file(registry_dir, output) do
    new_path = Path.join(registry_dir, @registry_file)
    legacy_path = Path.join(registry_dir, @legacy_registry_file)

    cond do
      File.exists?(new_path) ->
        call(output, :success, "✓ registry file (#{@registry_file})")

      File.exists?(legacy_path) ->
        call(output, :warn, "✗ registry file — 旧名 #{@legacy_registry_file} のみ存在します（読み取りは可能）")

      true ->
        call(
          output,
          :warn,
          "✗ registry file — #{@registry_file} が #{registry_dir} に見つかりません"
        )
    end
  end

  defp check_cache_dir(cache_dir, output) do
    expanded = Path.expand(cache_dir)

    case File.mkdir_p(expanded) do
      :ok -> call(output, :success, "✓ cache dir (#{expanded})")
      {:error, reason} -> call(output, :warn, "✗ cache dir #{expanded} — #{reason}")
    end
  end

  # --- 仕上げ ---

  defp show_next_steps(params, output) do
    config_flag =
      if params.config_path == default_config_path(false),
        do: "",
        else: " --config #{params.config_path}"

    call(output, :puts, "\nNext: thesis-monitor status#{config_flag}")
  end

  # --- helpers ---

  defp default_gh(args) do
    case System.cmd("gh", args, stderr_to_stdout: true) do
      {out, 0} -> {:ok, out}
      {out, _} -> {:error, out}
    end
  rescue
    e in ErlangError -> {:error, "gh command not found: #{inspect(e)}"}
  end

  defp call(output, fun, msg) when is_atom(output), do: apply(output, fun, [msg])
  defp call(output, fun, msg) when is_map(output), do: output[fun].(msg)
end
